import "./globals.css";
import type { Metadata } from "next";
import { Nunito, Outfit } from "next/font/google";
import AppProvider from "@/providers/AppProvider";


const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
});

const outfit = Outfit({
    variable: "--font-outfit",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${outfit.variable} antialiased`}
        >
            <head>
                {/* FontAwesome Free CDN */}
                <link
                    rel="stylesheet"
                    href="/fontawesome/css/all.min.css"
                />
            </head>
            <body>
                <AppProvider>{children}</AppProvider>
            </body>
        </html>
    );
}
